#ifndef ENTITY_TABLE_H
#define ENTITY_TABLE_H

#ifdef __cplusplus
extern "C" {
#endif

// @DOC: act as index for entity_template_get()
//       ! if out of order entities will be loaded as the wrong entity
typedef enum entity_template_type 
{
  ENTITY_TEMPLATE_QUAD,
  ENTITY_TEMPLATE_SPHERE01,
  ENTITY_TEMPLATE_SPHERE02,
  ENTITY_TEMPLATE_DEMON01,
  ENTITY_TEMPLATE_SHOTGUN,
  ENTITY_TEMPLATE_DEMON02,
  ENTITY_TEMPLATE_STONE01,
  ENTITY_TEMPLATE_TREE01,
  ENTITY_TEMPLATE_HUT_TEST,
  ENTITY_TEMPLATE_CUBE_STATIC,
  ENTITY_TEMPLATE_CUBE_DYNAMIC,
  ENTITY_TEMPLATE_PLAYER,
  ENTITY_TEMPLATE_CUBE_STATIC_TRIGGER,
  ENTITY_TEMPLATE_PALADIN_BODY,
  ENTITY_TEMPLATE_PALADIN_ARMOUR,
  ENTITY_TEMPLATE_PALADIN_WEAPON,
  ENTITY_TEMPLATE_SPHERE_DYN,
  ENTITY_TEMPLATE_PROJECTILE,
  ENTITY_TEMPLATE_ROBOT_CHARACTER_06,
  ENTITY_TEMPLATE_FEMALE_CHAR_01,
  ENTITY_TEMPLATE_FPS,
  ENTITY_TEMPLATE_MAX,

}entity_template_type;


#ifdef __cplusplus
} // extern C
#endif


#endif  // ENTITY_TABLE_H
