
# set(_ROOT_DIR_ ..)

# set(CMAKE_C_STANDARD 99)
# set(CMAKE_C_STANDARD_REQUIRED TRUE)

set(DEBUG_FLAGS "-g -Wall -DDebug -Ddebug -DDEBUG -DGLOBAL_DEBUG -DDEBUG_TIMER -DDEBUG_OPENGL -DDEBUG_DRAW -DPHYS_DEBUG")
set(RELEASE_FLAGS "-O3 -DRelease -Drelease -DRELEASE")
set(CMAKE_CXX_FLAGS_DEBUG_INIT   ${DEBUG_FLAGS})
set(CMAKE_CXX_FLAGS_RELEASE_INIT ${RELEASE_FLAGS})

set(CMAKE_C_FLAGS_DEBUG_INIT   ${DEBUG_FLAGS})
set(CMAKE_C_FLAGS_RELEASE_INIT ${RELEASE_FLAGS})


# puts .exe in _bin, but also dll's
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${ROOT_DIR}/_bin)
# set the output dir for libraries 
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${ROOT_DIR}/_libs/win64)   # static lib's
# set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${ROOT_DIR}/_libs/win64)   # dll's, should prob. be _bin
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${ROOT_DIR}/_bin)   # dll's

# -std=c99
set(CUSTOM_COMPILE_OPTIONS_EDITOR
  -g -Wall 
  -D_CRT_SECURE_NO_WARNINGS 
  -DASSETM_NO_ZIP
  -DEDITOR -DINCLUDE_PLAY_MODE
  # -DGLOBAL_DEBUG -DDEBUG_TIMER -DDEBUG_OPENGL -DDEBUG_DRAW -DPHYS_DEBUG  
  -DASSET_PATH=\"/Workspace/C/fisch/_assets/\"
  -DPF_PRINT_LOCATION 
  # -DTRACE_PRINT_LOCATION -DTRACE_LOG_PATH=\"trace.log\" -DTRACE_LOG_MAX_LINES=20 
  )

set(CUSTOM_COMPILE_OPTIONS
  -g -Wall 
  -D_CRT_SECURE_NO_WARNINGS
  # -DGLOBAL_DEBUG 
  -DASSETM_NO_ZIP 
  -DASSET_PATH=\"/Workspace/C/fisch/_assets/\"
  )

set(CUSTOM_COMPILE_FEATURES
  # cxx_std_11
  # c_std_99
  )

set(CUSTOM_INCLUDE_DIRS
  ${ROOT_DIR}/src 
  ${ROOT_DIR}/apps 
  ${ROOT_DIR}/games 
  ${ROOT_DIR}/_external 
  ${ROOT_DIR}/_external/FREETYPE
  )

