
# set(_ROOT_DIR_ ..)

# set(CMAKE_C_STANDARD 99)
# set(CMAKE_C_STANDARD_REQUIRED TRUE)

set(DEBUG_FLAGS "-g -Wall -DGLOBAL_DEBUG -DDEBUG_TIMER -DDEBUG_OPENGL -DDEBUG_DRAW -DPHYS_DEBUG")
set(RELEASE_FLAGS "")
set(CMAKE_CXX_FLAGS_DEBUG_INIT   ${DEBUG_FLAGS})
set(CMAKE_CXX_FLAGS_RELEASE_INIT ${RELEASE_FLAGS})

set(CMAKE_C_FLAGS_DEBUG_INIT   ${DEBUG_FLAGS})
set(CMAKE_C_FLAGS_RELEASE_INIT ${RELEASE_FLAGS})

# -std=c99
set(CUSTOM_COMPILE_OPTIONS_EDITOR
  -g -Wall 
  -D_CRT_SECURE_NO_WARNINGS 
  -DASSETM_NO_ZIP
  -DEDITOR -DINCLUDE_PLAY_MODE
  # -DGLOBAL_DEBUG -DDEBUG_TIMER -DDEBUG_OPENGL -DDEBUG_DRAW -DPHYS_DEBUG  
  -DASSET_PATH=\"/Workspace/C/fisch/_assets/\"
  -DPF_PRINT_LOCATION 
  # -DTRACE_PRINT_LOCATION -DTRACE_LOG_PATH=\"trace.log\" -DTRACE_LOG_MAX_LINES=20 
  )

set(CUSTOM_COMPILE_OPTIONS
  -g -Wall 
  -D_CRT_SECURE_NO_WARNINGS
  # -DGLOBAL_DEBUG 
  -DASSETM_NO_ZIP 
  -DASSET_PATH=\"/Workspace/C/fisch/_assets/\"
  )

set(CUSTOM_COMPILE_FEATURES
  cxx_std_11
  # c_std_99
  )

set(CUSTOM_INCLUDE_DIRS
  ../../src 
  ../../apps 
  ../../games 
  ../../_external 
  ../../_external/FREETYPE
  )

